version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: America/Los_Angeles
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
