name: DeathSpectating
author: RoboMWM
version: '${project.version}-${git.commit.id.abbrev}'
main: com.robomwm.deathspectating.DeathSpectating
website: https://github.com/MLG-Fortress/DeathSpectating/
softdepend: [Multiverse-Core, MultiWorld]
api-version: '1.13'
permissions:
    deathspectating.*:
        description: Grants ALL THE THINGS
        children:
            deathspectating.spectate: true
            deathspectating.commands: true
    deathspectating.spectate:
        description: Permission to enter death spectating mode. Permission has no effect if not enabled in config.
        default: false
    deathspectating.commands:
        description: Permission to use any command (that the player has permission to) while death spectating.
        default: op
